[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "codexia-contracts"
version = "0.1.0"
description = "Pydantic v2 contracts for Codexia"
requires-python = ">=3.11"
dependencies = ["pydantic>=2.8", "pydantic-settings>=2.3"]

[tool.black]
line-length = 100

[tool.ruff]
line-length = 100
select = ["E","F","I","UP"]

[tool.mypy]
python_version = "3.11"
strict = true
